name: 'sage_intacct_source'
version: '0.4.1'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
models:
  sage_intacct_source:
    +schema: sage_intacct_staging
    +materialized: table
    tmp:
      +materialized: view
vars:
  sage_intacct_source:
    gl_detail: "{{ source('sage_intacct','gl_detail') }}"
    gl_batch: "{{ source('sage_intacct','gl_batch') }}"
    gl_account: "{{ source('sage_intacct','gl_account') }}"
    ap_bill_item: "{{ source('sage_intacct','ap_bill_item') }}"
    ap_bill: "{{ source('sage_intacct','ap_bill') }}"
    ar_invoice_item: "{{ source('sage_intacct','ar_invoice_item') }}"
    ar_invoice: "{{ source('sage_intacct','ar_invoice') }}"
    sage_account_pass_through_columns: []
    sage_gl_pass_through_columns: []
    sage_intacct__using_bills: true
    sage_intacct__using_invoices: true
clean-targets:
- target
- dbt_modules
