
name: 'sage_intacct_source_integration_tests'
version: '0.2.0'
config-version: 2

profile: 'integration_tests' 

vars:
  sage_intacct_source:
    gl_detail:                    "{{ ref('sage_intacct__gl_detail') }}"
    gl_account:                   "{{ ref('sage_intacct__gl_account') }}"
    ap_bill_item:                 "{{ ref('sage_intacct__ap_bill_item') }}"
    ap_bill:                      "{{ ref('sage_intacct__ap_bill') }}"
    ar_invoice_item:              "{{ ref('sage_intacct__ar_invoice_item') }}"
    ar_invoice:                   "{{ ref('sage_intacct__ar_invoice') }}"

seeds:
  +quote_columns: "{{ true if target.type == 'redshift' else false }}"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']
