
name: 'sage_intacct_source_integration_tests'
version: '0.2.0'
config-version: 2

profile: 'integration_tests' 

vars:
  sage_intacct_source:
    sage_intacct_gl_detail_identifier:                    "sage_intacct__gl_detail"
    sage_intacct_gl_account_identifier:                   "sage_intacct__gl_account"
    sage_intacct_ap_bill_item_identifier:                 "sage_intacct__ap_bill_item"
    sage_intacct_ap_bill_identifier:                      "sage_intacct__ap_bill"
    sage_intacct_ar_invoice_item_identifier:              "sage_intacct__ar_invoice_item"
    sage_intacct_ar_invoice_identifier:                   "sage_intacct__ar_invoice"

    sage_intacct_schema: 'sage_intacct_source_integration_tests'

seeds:
  +quote_columns: "{{ true if target.type == 'redshift' else false }}"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']
