{% macro get_gl_account_columns() %}

{% set columns = [
    {"name": "_fivetran_deleted", "datatype": "boolean"},
    {"name": "_fivetran_synced", "datatype": dbt_utils.type_timestamp()},
    {"name": "accountno", "datatype": dbt_utils.type_string()},
    {"name": "accounttype", "datatype": dbt_utils.type_string()},
    {"name": "alternativeaccount", "datatype": dbt_utils.type_string()},
    {"name": "category", "datatype": dbt_utils.type_string()},
    {"name": "categorykey", "datatype": dbt_utils.type_int()},
    {"name": "cf_account_group", "datatype": dbt_utils.type_string()},
    {"name": "cf_bs_account_group", "datatype": dbt_utils.type_string()},
    {"name": "cf_bs_account_name", "datatype": dbt_utils.type_string()},
    {"name": "cf_bs_account_number", "datatype": dbt_utils.type_int()},
    {"name": "cf_bs_group_1", "datatype": dbt_utils.type_string()},
    {"name": "cf_bs_group_2", "datatype": dbt_utils.type_string()},
    {"name": "cf_bs_group_3", "datatype": dbt_utils.type_string()},
    {"name": "cf_bs_group_4", "datatype": dbt_utils.type_string()},
    {"name": "cf_bs_group_5", "datatype": dbt_utils.type_string()},
    {"name": "cf_bs_order_detail", "datatype": dbt_utils.type_int()},
    {"name": "cf_bs_order_summary", "datatype": dbt_utils.type_int()},
    {"name": "cf_category", "datatype": dbt_utils.type_string()},
    {"name": "cf_fs_group_1", "datatype": dbt_utils.type_string()},
    {"name": "cf_fs_group_2", "datatype": dbt_utils.type_string()},
    {"name": "cf_fs_group_3", "datatype": dbt_utils.type_string()},
    {"name": "cf_fs_group_4", "datatype": dbt_utils.type_string()},
    {"name": "cf_fs_group_5", "datatype": dbt_utils.type_string()},
    {"name": "cf_header_account", "datatype": "boolean"},
    {"name": "cf_is_order_detail", "datatype": dbt_utils.type_int()},
    {"name": "cf_is_order_summary", "datatype": dbt_utils.type_int()},
    {"name": "cf_legacy_coa", "datatype": dbt_utils.type_string()},
    {"name": "cf_legacy_mapping_notes", "datatype": dbt_utils.type_string()},
    {"name": "cf_reporting_group_1", "datatype": dbt_utils.type_string()},
    {"name": "cf_verano_account_group", "datatype": dbt_utils.type_string()},
    {"name": "closetoacctkey", "datatype": dbt_utils.type_int()},
    {"name": "closingaccountno", "datatype": dbt_utils.type_int()},
    {"name": "closingaccounttitle", "datatype": dbt_utils.type_string()},
    {"name": "closingtype", "datatype": dbt_utils.type_string()},
    {"name": "createdby", "datatype": dbt_utils.type_int()},
    {"name": "modifiedby", "datatype": dbt_utils.type_int()},
    {"name": "normalbalance", "datatype": dbt_utils.type_string()},
    {"name": "recordno", "datatype": dbt_utils.type_int()},
    {"name": "requireclass", "datatype": "boolean"},
    {"name": "requirecustomer", "datatype": "boolean"},
    {"name": "requiredept", "datatype": "boolean"},
    {"name": "requireemployee", "datatype": "boolean"},
    {"name": "requireitem", "datatype": "boolean"},
    {"name": "requireloc", "datatype": "boolean"},
    {"name": "requireproject", "datatype": "boolean"},
    {"name": "requirevendor", "datatype": "boolean"},
    {"name": "requirewarehouse", "datatype": "boolean"},
    {"name": "status", "datatype": dbt_utils.type_string()},
    {"name": "subledgercontrolon", "datatype": "boolean"},
    {"name": "taxable", "datatype": "boolean"},
    {"name": "testtext_area", "datatype": dbt_utils.type_string()},
    {"name": "title", "datatype": dbt_utils.type_string()},
    {"name": "whencreated", "datatype": dbt_utils.type_timestamp()},
    {"name": "whenmodified", "datatype": dbt_utils.type_timestamp()}
] %}

{{ return(columns) }}

{% endmacro %}
