23:01:33  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.develop.example

{% macro get_ap_bill_columns() %}

{% set columns = [
    {"name": "_fivetran_deleted", "datatype": "boolean"},
    {"name": "_fivetran_synced", "datatype": dbt_utils.type_timestamp()},
    {"name": "auwhencreated", "datatype": dbt_utils.type_timestamp()},
    {"name": "basecurr", "datatype": dbt_utils.type_string()},
    {"name": "billbacktemplate", "datatype": dbt_utils.type_string()},
    {"name": "billtopaytocontactname", "datatype": dbt_utils.type_string()},
    {"name": "billtopaytokey", "datatype": dbt_utils.type_int()},
    {"name": "createdby", "datatype": dbt_utils.type_int()},
    {"name": "currency", "datatype": dbt_utils.type_string()},
    {"name": "description", "datatype": dbt_utils.type_string()},
    {"name": "description_2", "datatype": dbt_utils.type_string()},
    {"name": "docnumber", "datatype": dbt_utils.type_string()},
    {"name": "due_in_days", "datatype": dbt_utils.type_int()},
    {"name": "expensify_memo_vb", "datatype": dbt_utils.type_string()},
    {"name": "financialentity", "datatype": dbt_utils.type_string()},
    {"name": "form_1099_box", "datatype": dbt_utils.type_int()},
    {"name": "form_1099_type", "datatype": dbt_utils.type_string()},
    {"name": "inclusivetax", "datatype": "boolean"},
    {"name": "megaentityid", "datatype": dbt_utils.type_string()},
    {"name": "megaentitykey", "datatype": dbt_utils.type_int()},
    {"name": "megaentityname", "datatype": dbt_utils.type_string()},
    {"name": "modifiedby", "datatype": dbt_utils.type_int()},
    {"name": "modulekey", "datatype": dbt_utils.type_string()},
    {"name": "onhold", "datatype": "boolean"},
    {"name": "paymentpriority", "datatype": dbt_utils.type_string()},
    {"name": "prbatch", "datatype": dbt_utils.type_string()},
    {"name": "prbatchkey", "datatype": dbt_utils.type_int()},
    {"name": "rawstate", "datatype": dbt_utils.type_string()},
    {"name": "recordid", "datatype": dbt_utils.type_string()},
    {"name": "recordno", "datatype": dbt_utils.type_string()},
    {"name": "recordtype", "datatype": dbt_utils.type_string()},
    {"name": "recpaymentdate", "datatype": "date"},
    {"name": "schopkey", "datatype": dbt_utils.type_int()},
    {"name": "shiptoreturntocontactname", "datatype": dbt_utils.type_string()},
    {"name": "shiptoreturntokey", "datatype": dbt_utils.type_int()},
    {"name": "stampli_link", "datatype": dbt_utils.type_string()},
    {"name": "state", "datatype": dbt_utils.type_string()},
    {"name": "supdocid", "datatype": dbt_utils.type_string()},
    {"name": "systemgenerated", "datatype": "boolean"},
    {"name": "termkey", "datatype": dbt_utils.type_int()},
    {"name": "termname", "datatype": dbt_utils.type_string()},
    {"name": "termvalue", "datatype": dbt_utils.type_string()},
    {"name": "totaldue", "datatype": dbt_utils.type_float()},
    {"name": "totalentered", "datatype": dbt_utils.type_float()},
    {"name": "totalpaid", "datatype": dbt_utils.type_float()},
    {"name": "totalretained", "datatype": dbt_utils.type_int()},
    {"name": "totalselected", "datatype": dbt_utils.type_float()},
    {"name": "trx_entitydue", "datatype": dbt_utils.type_float()},
    {"name": "trx_totaldue", "datatype": dbt_utils.type_float()},
    {"name": "trx_totalentered", "datatype": dbt_utils.type_float()},
    {"name": "trx_totalpaid", "datatype": dbt_utils.type_float()},
    {"name": "trx_totalreleased", "datatype": dbt_utils.type_int()},
    {"name": "trx_totalretained", "datatype": dbt_utils.type_int()},
    {"name": "trx_totalselected", "datatype": dbt_utils.type_float()},
    {"name": "vendorid", "datatype": dbt_utils.type_string()},
    {"name": "vendorname", "datatype": dbt_utils.type_string()},
    {"name": "whencreated", "datatype": "date"},
    {"name": "whendiscount", "datatype": "date"},
    {"name": "whendue", "datatype": "date"},
    {"name": "whenmodified", "datatype": dbt_utils.type_timestamp()},
    {"name": "whenpaid", "datatype": "date"},
    {"name": "whenposted", "datatype": "date"}
] %}

{{ return(columns) }}

{% endmacro %}
