{% macro get_gl_detail_columns() %}

{% set columns = [
    {"name": "_fivetran_deleted", "datatype": "boolean"},
    {"name": "_fivetran_synced", "datatype": dbt_utils.type_timestamp()},
    {"name": "accountno", "datatype": dbt_utils.type_float()},
    {"name": "accounttitle", "datatype": dbt_utils.type_string()},
    {"name": "amount", "datatype": dbt_utils.type_float()},
    {"name": "basecurr", "datatype": dbt_utils.type_string()},
    {"name": "batch_date", "datatype": "date"},
    {"name": "batch_no", "datatype": dbt_utils.type_int()},
    {"name": "batch_title", "datatype": dbt_utils.type_string()},
    {"name": "batchkey", "datatype": dbt_utils.type_string()},
    {"name": "bookid", "datatype": dbt_utils.type_string()},
    {"name": "creditamount", "datatype": dbt_utils.type_float()},
    {"name": "currency", "datatype": dbt_utils.type_string()},
    {"name": "customerid", "datatype": dbt_utils.type_string()},
    {"name": "customername", "datatype": dbt_utils.type_string()},
    {"name": "debitamount", "datatype": dbt_utils.type_float()},
    {"name": "description", "datatype": dbt_utils.type_string()},
    {"name": "docnumber", "datatype": dbt_utils.type_string()},
    {"name": "document", "datatype": dbt_utils.type_string()},
    {"name": "entry_date", "datatype": "date"},
    {"name": "entry_state", "datatype": dbt_utils.type_string()},
    {"name": "entrydescription", "datatype": dbt_utils.type_string()},
    {"name": "line_no", "datatype": dbt_utils.type_int()},
    {"name": "locationid", "datatype": dbt_utils.type_string()},
    {"name": "locationname", "datatype": dbt_utils.type_string()},
    {"name": "modified", "datatype": dbt_utils.type_timestamp()},
    {"name": "recordid", "datatype": dbt_utils.type_string()},
    {"name": "recordno", "datatype": dbt_utils.type_string()},
    {"name": "recordtype", "datatype": dbt_utils.type_string()},
    {"name": "totaldue", "datatype": dbt_utils.type_float()},
    {"name": "totalentered", "datatype": dbt_utils.type_float()},
    {"name": "totalpaid", "datatype": dbt_utils.type_float()},
    {"name": "tr_type", "datatype": dbt_utils.type_int()},
    {"name": "trx_amount", "datatype": dbt_utils.type_float()},
    {"name": "trx_creditamount", "datatype": dbt_utils.type_float()},
    {"name": "trx_debitamount", "datatype": dbt_utils.type_float()},
    {"name": "vendorid", "datatype": dbt_utils.type_string()},
    {"name": "vendorname", "datatype": dbt_utils.type_string()},
    {"name": "whencreated", "datatype": "date"},
    {"name": "whendue", "datatype": "date"},
    {"name": "whenmodified", "datatype": dbt_utils.type_timestamp()},
    {"name": "whenpaid", "datatype": "date"}
] %}

{{ return(columns) }}

{% endmacro %}
