{% macro get_location_columns() %}

{% set columns = [
    {"name": "_fivetran_deleted", "datatype": "boolean"},
    {"name": "_fivetran_synced", "datatype": dbt_utils.type_timestamp()},
    {"name": "businessdays", "datatype": dbt_utils.type_string()},
    {"name": "cf_cip_allowed", "datatype": "boolean"},
    {"name": "cf_internal_categorization", "datatype": dbt_utils.type_string()},
    {"name": "cf_internal_region", "datatype": dbt_utils.type_string()},
    {"name": "contactinfo_contactname", "datatype": dbt_utils.type_string()},
    {"name": "contactinfo_email_1", "datatype": dbt_utils.type_string()},
    {"name": "contactinfo_mailaddress_address_1", "datatype": dbt_utils.type_string()},
    {"name": "contactinfo_mailaddress_address_2", "datatype": dbt_utils.type_string()},
    {"name": "contactinfo_mailaddress_city", "datatype": dbt_utils.type_string()},
    {"name": "contactinfo_mailaddress_country", "datatype": dbt_utils.type_string()},
    {"name": "contactinfo_mailaddress_countrycode", "datatype": dbt_utils.type_string()},
    {"name": "contactinfo_mailaddress_state", "datatype": dbt_utils.type_string()},
    {"name": "contactinfo_mailaddress_zip", "datatype": dbt_utils.type_string()},
    {"name": "contactinfo_phone_1", "datatype": dbt_utils.type_string()},
    {"name": "contactinfo_printas", "datatype": dbt_utils.type_string()},
    {"name": "contactkey", "datatype": dbt_utils.type_int()},
    {"name": "createdby", "datatype": dbt_utils.type_int()},
    {"name": "custentity", "datatype": dbt_utils.type_string()},
    {"name": "customerid", "datatype": dbt_utils.type_string()},
    {"name": "customername", "datatype": dbt_utils.type_string()},
    {"name": "custtitle", "datatype": dbt_utils.type_string()},
    {"name": "federalid", "datatype": dbt_utils.type_string()},
    {"name": "firstmonth", "datatype": dbt_utils.type_int()},
    {"name": "firstmonthtax", "datatype": dbt_utils.type_int()},
    {"name": "has_ie_relation", "datatype": "boolean"},
    {"name": "isroot", "datatype": "boolean"},
    {"name": "locationid", "datatype": dbt_utils.type_string()},
    {"name": "modifiedby", "datatype": dbt_utils.type_int()},
    {"name": "name", "datatype": dbt_utils.type_string()},
    {"name": "parentid", "datatype": dbt_utils.type_string()},
    {"name": "parentkey", "datatype": dbt_utils.type_int()},
    {"name": "recordno", "datatype": dbt_utils.type_int()},
    {"name": "reportprintas", "datatype": dbt_utils.type_string()},
    {"name": "shipto_contactname", "datatype": dbt_utils.type_string()},
    {"name": "shipto_mailaddress_address_1", "datatype": dbt_utils.type_string()},
    {"name": "shipto_mailaddress_city", "datatype": dbt_utils.type_string()},
    {"name": "shipto_mailaddress_country", "datatype": dbt_utils.type_string()},
    {"name": "shipto_mailaddress_countrycode", "datatype": dbt_utils.type_string()},
    {"name": "shipto_mailaddress_state", "datatype": dbt_utils.type_string()},
    {"name": "shipto_mailaddress_zip", "datatype": dbt_utils.type_string()},
    {"name": "shipto_phone_1", "datatype": dbt_utils.type_string()},
    {"name": "shiptokey", "datatype": dbt_utils.type_int()},
    {"name": "status", "datatype": dbt_utils.type_string()},
    {"name": "supervisorid", "datatype": dbt_utils.type_string()},
    {"name": "supervisorkey", "datatype": dbt_utils.type_int()},
    {"name": "supervisorname", "datatype": dbt_utils.type_string()},
    {"name": "taxid", "datatype": dbt_utils.type_string()},
    {"name": "vendentity", "datatype": dbt_utils.type_string()},
    {"name": "vendorid", "datatype": dbt_utils.type_string()},
    {"name": "vendorname", "datatype": dbt_utils.type_string()},
    {"name": "weekends", "datatype": dbt_utils.type_string()},
    {"name": "weekstart", "datatype": dbt_utils.type_int()},
    {"name": "whencreated", "datatype": dbt_utils.type_timestamp()},
    {"name": "whenmodified", "datatype": dbt_utils.type_timestamp()}
] %}

{{ return(columns) }}

{% endmacro %}
