
with base as (

    select * 
    from {{ ref('stg_sage_intacct__vendor_tmp') }}

),

fields as (

    select
        {{
            fivetran_utils.fill_staging_columns(
                source_columns=adapter.get_columns_in_relation(ref('stg_sage_intacct__vendor_tmp')),
                staging_columns=get_vendor_columns()
            )
        }}
        
    from base
),

final as (
    
    select 

    vendorid,
    _fivetran_deleted,
    _fivetran_synced,
    billingtype,
    checkenabled,
    createdby,
    displaycontactkey,
    displaytermdiscount,
    displocacctnocheck,
    donotcutcheck,
    entity,
    isowner,
    mergepaymentreq,
    modifiedby,
    name,
    objectrestriction,
    onetime,
    onhold,
    parentid,
    parentkey,
    parentname,
    paymentnotify,
    paymentpriority,
    recordno,
    status,
    supdocid,
    taxid,
    termname,
    termskey,
    termvalue,
    totaldue,
    vendoraccountno,
    vendoracctnokey,
    whencreated,
    whenmodified,
    wireenabled,
    form_1099_box,
    vendtype,
    comments,
    apaccounttitle,
    vendtypekey,
    form_1099_type,
    returntokey,
    apaccount,
    accountkey,
    name_1099,
    paymethodkey,
    paymethodrec,
    achremittancetype,
    cf_altmed_payment,
    achbankroutingnumber,
    megaentityname,
    megaentitykey,
    megaentityid,
    achaccounttype,
    achaccountnumber,
    achenabled,
    paydatevalue,
    paytokey,
    cf_ato_number,
    glgroup,
    glgrpkey,
    payto_mailaddress_city,
    displaycontact_taxable,
    displaycontact_lastname,
    payto_mailaddress_country,
    returnto_visible,
    returnto_printas,
    displaycontact_companyname,
    displaycontact_phone_2,
    displaycontact_visible,
    displaycontact_initial,
    returnto_companyname,
    displaycontact_url_1,
    payto_contactname,
    displaycontact_email_1,
    displaycontact_status,
    displaycontact_email_2,
    returnto_mailaddress_state,
    payto_mailaddress_zip,
    displaycontact_mailaddress_countrycode,
    payto_visible,
    payto_mailaddress_countrycode,
    displaycontact_mailaddress_state,
    payto_mailaddress_address_1,
    displaycontact_mailaddress_country,
    payto_mailaddress_address_2,
    displaycontact_mailaddress_city,
    returnto_mailaddress_countrycode,
    displaycontact_contactname,
    payto_mailaddress_state,
    payto_companyname,
    returnto_mailaddress_address_1,
    displaycontact_cellphone,
    returnto_mailaddress_zip,
    returnto_mailaddress_address_2,
    displaycontact_fax,
    returnto_contactname,
    returnto_mailaddress_country,
    returnto_mailaddress_cit,
    displaycontact_mailaddress_address_1,
    displaycontact_mailaddress_zip,
    displaycontact_mailaddress_address_2,
    payto_printas,
    displaycontact_phone_1,
    displaycontact_firstname,
    displaycontact_printas,
    payto_phone_1,
    contactinfo_mailaddress_zip,
    primarycontactkey,
    contactinfo_mailaddress_address_2,
    contactinfo_visible,
    contactinfo_mailaddress_country,
    contactinfo_mailaddress_address_1,
    contactinfo_contactname,
    contactinfo_mailaddress_city,
    contactinfo_mailaddress_countrycode,
    contactinfo_printas,
    contactinfo_mailaddress_state,
    offsetglaccountnotitle,
    offsetglaccountno,
    displaycontact_pager,
    filepaymentservice,
    isindividual,
    displaycontact_prefix,
    returnto_phone_1,
    returnto_lastname,
    returnto_email_1,
    returnto_firstname,
    cf_billback_vendor,
    federal_tax_classification,
    cf_entity_private,
    cf_duplicate,
    creditlimit,
    contactto_1099_mailaddress_country,
    contactto_1099_contactname,
    contactto_1099_mailaddress_countrycode,
    contactto_1099_mailaddress_state,
    contactto_1099_printas,
    contactto_1099_mailaddress_zip,
    contactto_1099_companyname,
    contactto_1099_mailaddress_address_2,
    contactto_1099_mailaddress_city,
    contactto_1099_mailaddress_address_1,
    contactto_1099_visible,
    contactkey_109

    from fields
)

select * from final
